config/routes.rb
Rails.application.routes.draw do
  get 'users/:username', to: 'users#show', as: 'user'

  resources :items
  resources :credentialing_documents
  resources :tweets
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
    get "signin", to: 'devise/sessions#new'
    delete "signout", to: 'devise/sessions#destroy'
    get "signup", to: 'devise/registrations#new'
  end
  root 'pages#home'
  get  'about', to: 'pages#about'
  get  'contact', to: 'pages#contact'

end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter
	
	def authorized?(action, subject = nil)
		user && user.admin?
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/credentialing_document.rb
class CredentialingDocument < ApplicationRecord
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :tweets   
  has_many :items
  has_many :credentialing_documents  
  validates :username, presence: true, uniqueness: true, length: { minimum: 6 } 
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  def access_denied(exception)
  	redirect_to root_path, alert: exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
  end
end

app/controllers/credentialing_documents_controller.rb
class CredentialingDocumentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /credentialing_documents
  def index
    @credentialing_documents = CredentialingDocument.all
  end

  # GET /credentialing_documents/1
  def show
    @credentialing_document = CredentialingDocument.find(params[:id])
  end

  # GET /credentialing_documents/new
  def new
    @credentialing_document = current_user.credentialing_documents.new
  end

  # GET /credentialing_documents/1/edit
  def edit
    @credentialing_document = current_user.credentialing_documents.find(params[:id])
  end

  # POST /credentialing_documents
  def create
    @credentialing_document = current_user.credentialing_documents.new(item_params)

    if @credentialing_document.save
        redirect_to @credentialing_document, notice: 'Credentialing document was successfully created.' 
    else
      render :new 
    end
  end

  # PATCH/PUT /credentialing_documents/1
  def update
    @credentialing_document = current_user.credentialing_documents.find(params[:id])
    if @credentialing_document.update(credentialing_document_params)
      redirect_to @credentialing_document, notice: 'Credentialing document was successfully updated.' 
    else
      render :edit 
    end
  end

  # DELETE /credentialing_documents/1
  def destroy
    @credentialing_document = current_user.credentialing_documents.find(prarams[:id])
    @credentialing_document.destroy
    redirect_to credentialing_documents_url, notice: 'Credentialing document was successfully destroyed.' 
    end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def credentialing_document_params
      params.require(:credentialing_document).permit(:filename, :content_type, :file_contents)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /items
  def index
    @items = Item.all
  end

  # GET /items/1
  def show
    @item = Item.find(params[:id])
  end

  # GET /items/new
  def new
    @item = current_user.items.new
  end

  # GET /items/1/edit
  def edit
    @item = current_user.items.find(params[:id])
  end

  # POST /items
  def create
    @item = current_user.items.new(item_params)
    
    if @item.save
      redirect_to @item, notice: 'Item was successfully created.' 
    else
      render :new 
    end
  end

  # PATCH/PUT /items/1
  def update
    @item = current_user.items.find(params[:id])
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.' 
    else
      render :edit 
    end
  end

  # DELETE /items/1
  def destroy
    @item = current_user.items.find(params[:id])
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.' 
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :url, :text)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = current_user.tweets.find(params[:id])
  end

  # POST /tweets
  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find_by(username: params[:username])
  	@tweets = @user.tweets
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credentialing_documents_helper.rb
module CredentialingDocumentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/credentialing_documents/_form.html.erb
  <%= form_for(credentialing_document) do |f| %>
    <% if credentialing_document.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(credentialing_document.errors.count, "error") %> prohibited this credentialing_document from being saved:</h2>

        <ul>
        <% credentialing_document.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :filename %>
      <%= f.text_field :filename %>
    </div>

    <div class="field">
      <%= f.label :content_type %>
      <%= f.text_field :content_type %>
    </div>

    <div class="field">
      <%= f.label :file_contents %>
      <%= f.text_field :file_contents %>
    </div>

    <div class="actions">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/credentialing_documents/edit.html.erb
<div class="container">
	<h1>Editing Credentialing Document</h1>

	<%= render 'form', credentialing_document: @credentialing_document %>

	<%= link_to 'Show', @credentialing_document %> |
	<%= link_to 'Back', credentialing_documents_path %>
</div>

app/views/credentialing_documents/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Credentialing Documents</h1>

  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th>Document Title</th>
        <th>Document Details</th>
        <th>File contents</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @credentialing_documents.each do |credentialing_document| %>
        <% if @credentialing_document.user == current_user %>
          <tr>
            <td><%= credentialing_document.filename %></td>
            <td><%= credentialing_document.content_type %></td>
            <td><%= credentialing_document.file_contents %></td>
            <td><%= link_to 'Show', credentialing_document %></td>
            <td><%= link_to 'Edit', edit_credentialing_document_path(credentialing_document) %></td>
            <td><%= link_to 'Destroy', credentialing_document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Credentialing Document', new_credentialing_document_path %>
</div>

app/views/credentialing_documents/new.html.erb
<div class="container">
	<h1>New Credentialing Document</h1>

	<%= render 'form', credentialing_document: @credentialing_document %>

	<%= link_to 'Back', credentialing_documents_path %>
</div>

app/views/credentialing_documents/show.html.erb
<div class="container">	
	<p id="notice"><%= notice %></p>

	<p>
	  <strong>Filename:</strong>
	  <%= @credentialing_document.filename %>
	</p>

	<p>
	  <strong>Content type:</strong>
	  <%= @credentialing_document.content_type %>
	</p>

	<p>
	  <strong>File contents:</strong>
	  <%= @credentialing_document.file_contents %>
	</p>

	<%= link_to 'Edit', edit_credentialing_document_path(@credentialing_document) %> |
	<%= link_to 'Back', credentialing_documents_path %>
</div>

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: "form-control" %>
  </div>

  <p><strong>or</strong></p>

  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text, class: "form-control" %>
  </div>
    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/items/edit.html.erb
<div class="container">
	<h1>Editing Item</h1>

	<%= render 'form', item: @item %>

	<%= link_to 'Show', @item %> |
	<%= link_to 'Back', items_path %>
</div>

app/views/items/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Items</h1>

  <table>
    <thead>
      <tr>
        <th>User</th>
        <th>Title</th>
        <th>Url</th>
        <th>Text</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @items.each do |item| %>
        <tr>
          <td><%= item.user.username %></td>
          <td><%= item.title %></td>
          <td><%= item.url %></td>
          <td><%= item.text %></td>
          <td><%= link_to 'Show', item %></td>
          <% if item.user == current_user %>
            <td><%= link_to 'Edit', edit_item_path(item) %></td>
            <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Item', new_item_path %>
</div>

app/views/items/new.html.erb
<div class="container">
	<h1>New Item</h1>

	<%= render 'form', item: @item %>

	<%= link_to 'Back', items_path %>
</div>

app/views/items/show.html.erb
<div class="container">

	<p>
	  <strong>User:</strong>
	  <%= @item.user.username %>
	</p>

	<p>
	  <strong>Title:</strong>
	  <%= @item.title %>
	</p>

	<% if @item.url? %>
		<p>
		  <strong>Url:</strong>
		  <%= @item.url %>
		</p>
	<% end %>

	<% if @item.text? %>
		<p>
		  <strong>Text:</strong>
		  <%= @item.text %>
		</p>
	<% end %>

	<% if @item.user == current_user %>
		<%= link_to 'Edit', edit_item_path(@item) %> |
	<% end %>	
		<%= link_to 'Back', items_path %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>One Month Rails Project</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-dark bg-inverse">
      <div class="container">
        <ul class="nav navbar-nav">
            <li class="nav-item"><%= link_to image_tag("logo-horizontal-white copy.png", size: "150x45", :alt => "AMPA logo"), root_path %></li>
            <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "Contact", contact_path, class: "nav-link" %></li>
            <% if user_signed_in? %>
              <li class="nav-item pull-md-right"><%= link_to "Log Out", signout_path, method: :delete, class: "nav-link" %>
              </li>
            <% else %>
              <li class="nav-item pull-md-right"><%= link_to "Sign Up", signup_path, class: "btn btn-warning" %>
              </li>
              <li class="nav-item pull-md-right"><%= link_to "Log In", signin_path, class: "nav-link" %>
              </li>
            <% end %>
        </ul>
      </div>
    </nav>

    <!-- Flash Messages -->
    <% flash.each do |name, message| %>
      <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
    <% end %>

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2016 American Medical Professions Association</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="row">
  <div class="col-xs-6 col-md-3">
    <%= link_to image_tag("logo-horizontal-white copy.png", size: "150x45", :alt => "AMPA logo"), root_path %>
  </div>
  ...
</div>

app/views/pages/contact.html.erb
<div class="container">
	<h1>Contact Us</h1>
		<p>7878 N. 16th St. STE 250 | Phoenix, AZ 85020</p>
		<p>602-308-7848</p>
		<p>info@ampadocs.com</p>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <div class="jumbotron jumbotron-home">
    <div class="container">
      <h1>Welcome Back!</h1>
    </div>
  </div>
<% else %>
  <div class="jumbotron jumbotron-home">
    <div class="container container-home">
      <!-- <h1>American Medical Professions Association</h1>    -->
           
          <!-- <%= link_to "Learn more »", "#", class: "btn btn-primary btn-sm" %> -->
    </div>
  </div>
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <h2>Manage Your CV</h2>
            <p>Build, manage, maintain and share your CV</p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
            <div class="col-md-3">
              <h2>Huge Discounts</h2>
                  <p>AMPA members enjoy group discounts on medical malpractice insurance, disability insurance, and workers compensation insurance. Our members have saved millions in premiums through these programs.</p>
                  <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
            </div>
              <div class="col-md-3">
                <h2>Credentialing Management</h2>
                  <p>Our HIPAA compliant secure platform gives medical professionals a safe place to manage their important credentialing documents and share them with facilities and vendors that require updated credentialing documents</p>
                  <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
              </div>
                <div class="col-md-3">
                  <h2>Network</h2>
                    <p>Find your colleagues, use our search tool to invite your colleagues and friends. Form groups within our secure platform and create private or public forums to discuss the issues you care most about. Post a job, look for a job, or share content you feel is important.</p>
                    <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
                </div>   
      </div>
    </div>
    <div class="container">

    </div>
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(tweet) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<div class="container">
	<h1>Editing Tweet</h1>

	<%= render 'form', tweet: @tweet %>

	<%= link_to 'Show', @tweet %> |
	<%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/index.html.erb
<div class="container">
  
  <div class="row">
    <div class="col-md-4">
      <div class="card card-block">
        <h4 class="card-title">Your Account</h4>
         <p class="card-text"> <%= current_user.username %> </p>
      </div>
    </div>
    <div class="col-md-8">
      <% if user_signed_in? %>
        <center><%= link_to 'New Tweet', new_tweet_path, class: "btn btn-primary" %></center>
      <% end %> 
      <ul class="list-group">
        <% @tweets.each do |tweet| %>
          <%= link_to tweet, class: "list-group-item list-group-item-action" do %>
            <h5 class="list-group-item-heading"><%= tweet.user.username %></h5>
            <p class="list-group-item-text"><%= tweet.content %></p>
          <% end %>
        <% end %>
      </ul>
    </div>  
  </div> 
</div>

app/views/tweets/new.html.erb
<div class="container">
	<h1>New Tweet</h1>

	<%= render 'form', tweet: @tweet %>

	<%= link_to 'Back', tweets_path %>
<div>

app/views/tweets/show.html.erb
<div class="container">
	<div class="row">
		<div class="offset-md-2 col-md-8"> 
			<div class="card card-block">
			  <h4 class="card-title"><%= link_to @tweet.user.username, user_path(@tweet.user.username) %></h4>
			  <p class="card-text"><%= @tweet.content %></p>
			  <% if @tweet.user == current_user %>
					<%= link_to 'Edit', edit_tweet_path(@tweet), class: "card-link" %>
					<%= link_to 'Delete', @tweet, method: :delete, class: "card-link" %>
				<% end %>
				<%= link_to 'Back', tweets_path, class: "card-link" %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <div class="card card-block">
        <h4 class="card-title"><%= @user.username %></h4>
         <p class="card-text"><%= @user.name %></p>
      </div>
    </div>
    <div class="col-md-8">
      <ul class="list-group">
        <% @tweets.each do |tweet| %>
          <%= link_to tweet, class: "list-group-item list-group-item-action" do %>
            <h5 class="list-group-item-heading"><%= tweet.user.username %></h5>
            <p class="list-group-item-text"><%= tweet.content %></p>
          <% end %>
        <% end %>
      </ul>
    </div>  
  </div> 
</div>